SELECT * FROM customer limit(20)

ALTER TABLE "customer"
RENAME COLUMN "Purchase_Amount_(USD)" TO "Purchase_Amount";

ALTER TABLE "customer"
RENAME COLUMN "Gender" TO "SEX";

ALTER TABLE "customer" RENAME COLUMN "SEX" TO sex;
ALTER TABLE "customer" RENAME COLUMN "Purchase_Amount" TO purchase_amount;
ALTER TABLE "customer" RENAME COLUMN "Shipping_Type" To shipping_type;
ALTER TABLE "customer" RENAME COLUMN "Subscription_Status" TO Subscription_status;
ALTER TABLE "customer" RENAME COLUMN "Previous_Purchases" TO previous_purchases;
--Q1.What is the total revenue generated by male vs.female customer?

SELECT sex, SUM(Purchase_Amount) as revenue
FROM customer
GROUP BY sex

ALTER TABLE customer RENAME COLUMN "Customer_ID" TO customer_id;
ALTER TABLE customer RENAME COLUMN "Discount_Applied" TO discount_applied;
ALTER TABLE customer RENAME COLUMN "Item_Purchased" TO item_purchased;
ALTER TABLE customer RENAME COLUMN "Category" TO category;
ALTER TABLE customer RENAME COLUMN "Location" TO location;



--Q2.which customers used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount 
FROM customer
WHERE discount_applied ='Yes' 
   AND purchase_amount >= (
   SELECT AVG(purchase_amount) FROM customer);

ALTER TABLE customer RENAME COLUMN "Item_Purchased" TO item_purchased;
ALTER TABLE customer RENAME COLUMN "Review_Rating" TO review_rating;

--Q3. which are the top 5 products with the highest average review rating 
SELECT item_purchased, ROUND(AVG (review_rating::numeric),2) AS "average product rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
limit 5;

--Q4. Compare the avg purchase amounts between standard and express shipping.
SELECT shipping_type,
AVG (purchase_amount)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

--Q5 Do Subscribed customers spend more? compare spend and total revenue bet subscribers and non-subs
SELECT subscription_status,
COUNT (customer_id) AS total_customers,
ROUND (AVG(purchase_amount),2) AS avg_spend,
ROUND (SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend desc; 

--Q6 which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
       ROUND(
           100.0 * 
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
           / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

Q7-- Segment customers into new, returing, and loyal on their total number of 
--previous purchases, and show the count of each segment 
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer	
)

SELECT customer_segment, count(*) AS "Number of customers"
FROM customer_type
GROUP BY customer_segment

--Q8 what are the top 3 most purchases products within each category?
WITH item_counts AS (
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER( ) OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) AS item_rank
FROM customer
GROUP BY category, item_purchased 
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9 are customers who are repeat buyers (more than 5 previous purchases)also likely to subscribe?
SELECT subscription_status,
COUNT (customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10 What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
